### ISSUE TITLE
Correspondence workflow fails, no warning to user

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/Arches_HER#748]
After selecting the consultation and letter type, the consultation workflow fails.  The workflow step just shows the spinner, and <incorrectly> enables the next step button.  

However the workflow fails with the following server error in django :

Internal Server Error: /filetemplate
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/dwuthrich/arches/arches_projects/arches-her/arches_her/views/file_template.py", line 85, in post
    self.edit_letter(self.resource, datatype_factory)
  File "/Users/dwuthrich/arches/arches_projects/arches-her/arches_her/views/file_template.py", line 193, in edit_letter
    self.replace_in_letter(consultation.tiles, template_dict, datatype_factory)
  File "/Users/dwuthrich/arches/arches_projects/arches-her/arches_her/views/file_template.py", line 257, in replace_in_letter
    caseAgentResourceiId = tile.data[contacts["Casework Officer"]][0]["resourceId"]
TypeError: 'NoneType' object is not subscriptable

Browser error is:

Uncaught TypeError: self.alert is not a function
    at Object.<anonymous> (correspondence-select-resource.js?_dc=6.0.0b0:129)
    at c (jquery.min.js?_dc=6.0.0b0:2)
    at Object.fireWith [as rejectWith] (jquery.min.js?_dc=6.0.0b0:2)
    at l (jquery.min.js?_dc=6.0.0b0:2)
    at XMLHttpRequest.<anonymous> (jquery.min.js?_dc=6.0.0b0:2)

**Comment by chiatt** [comment]
Fixed in #755
